<?php 
return [ 
		['id' => 1 , 'sort_name' => "AF" , 'name' => "Afghanistan" , 'd_code' => 93] , 
		['id' => 2 , 'sort_name' => "AL" , 'name' => "Albania" , 'd_code' => 355] , 
		['id' => 3 , 'sort_name' => "DZ" , 'name' => "Algeria" , 'd_code' => 213] , 
		['id' => 4 , 'sort_name' => "AS" , 'name' => "American Samoa" , 'd_code' => 1684] , 
		['id' => 5 , 'sort_name' => "AD" , 'name' => "Andorra" , 'd_code' => 376] , 
		['id' => 6 , 'sort_name' => "AO" , 'name' => "Angola" , 'd_code' => 244] , 
		['id' => 7 , 'sort_name' => "AI" , 'name' => "Anguilla" , 'd_code' => 1264] , 
		['id' => 8 , 'sort_name' => "AQ" , 'name' => "Antarctica" , 'd_code' => 0] , 
		['id' => 9 , 'sort_name' => "AG" , 'name' => "Antigua And Barbuda" , 'd_code' => 1268] , 
		['id' => 10 , 'sort_name' => "AR" , 'name' => "Argentina" , 'd_code' => 54] , 
		['id' => 11 , 'sort_name' => "AM" , 'name' => "Armenia" , 'd_code' => 374] , 
		['id' => 12 , 'sort_name' => "AW" , 'name' => "Aruba" , 'd_code' => 297] , 
		['id' => 13 , 'sort_name' => "AU" , 'name' => "Australia" , 'd_code' => 61] , 
		['id' => 14 , 'sort_name' => "AT" , 'name' => "Austria" , 'd_code' => 43] , 
		['id' => 15 , 'sort_name' => "AZ" , 'name' => "Azerbaijan" , 'd_code' => 994] , 
		['id' => 16 , 'sort_name' => "BS" , 'name' => "Bahamas The" , 'd_code' => 1242] , 
		['id' => 17 , 'sort_name' => "BH" , 'name' => "Bahrain" , 'd_code' => 973] , 
		['id' => 18 , 'sort_name' => "BD" , 'name' => "Bangladesh" , 'd_code' => 880] , 
		['id' => 19 , 'sort_name' => "BB" , 'name' => "Barbados" , 'd_code' => 1246] , 
		['id' => 20 , 'sort_name' => "BY" , 'name' => "Belarus" , 'd_code' => 375] , 
		['id' => 21 , 'sort_name' => "BE" , 'name' => "Belgium" , 'd_code' => 32] , 
		['id' => 22 , 'sort_name' => "BZ" , 'name' => "Belize" , 'd_code' => 501] , 
		['id' => 23 , 'sort_name' => "BJ" , 'name' => "Benin" , 'd_code' => 229] , 
		['id' => 24 , 'sort_name' => "BM" , 'name' => "Bermuda" , 'd_code' => 1441] , 
		['id' => 25 , 'sort_name' => "BT" , 'name' => "Bhutan" , 'd_code' => 975] , 
		['id' => 26 , 'sort_name' => "BO" , 'name' => "Bolivia" , 'd_code' => 591] , 
		['id' => 27 , 'sort_name' => "BA" , 'name' => "Bosnia and Herzegovina" , 'd_code' => 387] , 
		['id' => 28 , 'sort_name' => "BW" , 'name' => "Botswana" , 'd_code' => 267] , 
		['id' => 29 , 'sort_name' => "BV" , 'name' => "Bouvet Island" , 'd_code' => 0] , 
		['id' => 30 , 'sort_name' => "BR" , 'name' => "Brazil" , 'd_code' => 55] , 
		['id' => 31 , 'sort_name' => "IO" , 'name' => "British Indian Ocean Territory" , 'd_code' => 246] , 
		['id' => 32 , 'sort_name' => "BN" , 'name' => "Brunei" , 'd_code' => 673] , 
		['id' => 33 , 'sort_name' => "BG" , 'name' => "Bulgaria" , 'd_code' => 359] , 
		['id' => 34 , 'sort_name' => "BF" , 'name' => "Burkina Faso" , 'd_code' => 226] , 
		['id' => 35 , 'sort_name' => "BI" , 'name' => "Burundi" , 'd_code' => 257] , 
		['id' => 36 , 'sort_name' => "KH" , 'name' => "Cambodia" , 'd_code' => 855] , 
		['id' => 37 , 'sort_name' => "CM" , 'name' => "Cameroon" , 'd_code' => 237] , 
		['id' => 38 , 'sort_name' => "CA" , 'name' => "Canada" , 'd_code' => 1] , 
		['id' => 39 , 'sort_name' => "CV" , 'name' => "Cape Verde" , 'd_code' => 238] , 
		['id' => 40 , 'sort_name' => "KY" , 'name' => "Cayman Islands" , 'd_code' => 1345] , 
		['id' => 41 , 'sort_name' => "CF" , 'name' => "Central African Republic" , 'd_code' => 236] , 
		['id' => 42 , 'sort_name' => "TD" , 'name' => "Chad" , 'd_code' => 235] , 
		['id' => 43 , 'sort_name' => "CL" , 'name' => "Chile" , 'd_code' => 56] , 
		['id' => 44 , 'sort_name' => "CN" , 'name' => "China" , 'd_code' => 86] , 
		['id' => 45 , 'sort_name' => "CX" , 'name' => "Christmas Island" , 'd_code' => 61] , 
		['id' => 46 , 'sort_name' => "CC" , 'name' => "Cocos (Keeling) Islands" , 'd_code' => 672] , 
		['id' => 47 , 'sort_name' => "CO" , 'name' => "Colombia" , 'd_code' => 57] , 
		['id' => 48 , 'sort_name' => "KM" , 'name' => "Comoros" , 'd_code' => 269] , 
		['id' => 49 , 'sort_name' => "CG" , 'name' => "Republic Of The Congo" , 'd_code' => 242] , 
		['id' => 50 , 'sort_name' => "CD" , 'name' => "Democratic Republic Of The Congo" , 'd_code' => 242] , 
		['id' => 51 , 'sort_name' => "CK" , 'name' => "Cook Islands" , 'd_code' => 682] , 
		['id' => 52 , 'sort_name' => "CR" , 'name' => "Costa Rica" , 'd_code' => 506] , 
		['id' => 53 , 'sort_name' => "CI" , 'name' => "Cote D''Ivoire (Ivory Coast)" , 'd_code' => 225] , 
		['id' => 54 , 'sort_name' => "HR" , 'name' => "Croatia (Hrvatska)" , 'd_code' => 385] , 
		['id' => 55 , 'sort_name' => "CU" , 'name' => "Cuba" , 'd_code' => 53] , 
		['id' => 56 , 'sort_name' => "CY" , 'name' => "Cyprus" , 'd_code' => 357] , 
		['id' => 57 , 'sort_name' => "CZ" , 'name' => "Czech Republic" , 'd_code' => 420] , 
		['id' => 58 , 'sort_name' => "DK" , 'name' => "Denmark" , 'd_code' => 45] , 
		['id' => 59 , 'sort_name' => "DJ" , 'name' => "Djibouti" , 'd_code' => 253] , 
		['id' => 60 , 'sort_name' => "DM" , 'name' => "Dominica" , 'd_code' => 1767] , 
		['id' => 61 , 'sort_name' => "DO" , 'name' => "Dominican Republic" , 'd_code' => 1809] , 
		['id' => 62 , 'sort_name' => "TP" , 'name' => "East Timor" , 'd_code' => 670] , 
		['id' => 63 , 'sort_name' => "EC" , 'name' => "Ecuador" , 'd_code' => 593] , 
		['id' => 64 , 'sort_name' => "EG" , 'name' => "Egypt" , 'd_code' => 20] , 
		['id' => 65 , 'sort_name' => "SV" , 'name' => "El Salvador" , 'd_code' => 503] , 
		['id' => 66 , 'sort_name' => "GQ" , 'name' => "Equatorial Guinea" , 'd_code' => 240] , 
		['id' => 67 , 'sort_name' => "ER" , 'name' => "Eritrea" , 'd_code' => 291] , 
		['id' => 68 , 'sort_name' => "EE" , 'name' => "Estonia" , 'd_code' => 372] , 
		['id' => 69 , 'sort_name' => "ET" , 'name' => "Ethiopia" , 'd_code' => 251] , 
		['id' => 70 , 'sort_name' => "XA" , 'name' => "External Territories of Australia" , 'd_code' => 61] , 
		['id' => 71 , 'sort_name' => "FK" , 'name' => "Falkland Islands" , 'd_code' => 500] , 
		['id' => 72 , 'sort_name' => "FO" , 'name' => "Faroe Islands" , 'd_code' => 298] , 
		['id' => 73 , 'sort_name' => "FJ" , 'name' => "Fiji Islands" , 'd_code' => 679] , 
		['id' => 74 , 'sort_name' => "FI" , 'name' => "Finland" , 'd_code' => 358] , 
		['id' => 75 , 'sort_name' => "FR" , 'name' => "France" , 'd_code' => 33] , 
		['id' => 76 , 'sort_name' => "GF" , 'name' => "French Guiana" , 'd_code' => 594] , 
		['id' => 77 , 'sort_name' => "PF" , 'name' => "French Polynesia" , 'd_code' => 689] , 
		['id' => 78 , 'sort_name' => "TF" , 'name' => "French Southern Territories" , 'd_code' => 0] , 
		['id' => 79 , 'sort_name' => "GA" , 'name' => "Gabon" , 'd_code' => 241] , 
		['id' => 80 , 'sort_name' => "GM" , 'name' => "Gambia The" , 'd_code' => 220] , 
		['id' => 81 , 'sort_name' => "GE" , 'name' => "Georgia" , 'd_code' => 995] , 
		['id' => 82 , 'sort_name' => "DE" , 'name' => "Germany" , 'd_code' => 49] , 
		['id' => 83 , 'sort_name' => "GH" , 'name' => "Ghana" , 'd_code' => 233] , 
		['id' => 84 , 'sort_name' => "GI" , 'name' => "Gibraltar" , 'd_code' => 350] , 
		['id' => 85 , 'sort_name' => "GR" , 'name' => "Greece" , 'd_code' => 30] , 
		['id' => 86 , 'sort_name' => "GL" , 'name' => "Greenland" , 'd_code' => 299] , 
		['id' => 87 , 'sort_name' => "GD" , 'name' => "Grenada" , 'd_code' => 1473] , 
		['id' => 88 , 'sort_name' => "GP" , 'name' => "Guadeloupe" , 'd_code' => 590] , 
		['id' => 89 , 'sort_name' => "GU" , 'name' => "Guam" , 'd_code' => 1671] , 
		['id' => 90 , 'sort_name' => "GT" , 'name' => "Guatemala" , 'd_code' => 502] , 
		['id' => 91 , 'sort_name' => "XU" , 'name' => "Guernsey and Alderney" , 'd_code' => 44] , 
		['id' => 92 , 'sort_name' => "GN" , 'name' => "Guinea" , 'd_code' => 224] , 
		['id' => 93 , 'sort_name' => "GW" , 'name' => "Guinea-Bissau" , 'd_code' => 245] , 
		['id' => 94 , 'sort_name' => "GY" , 'name' => "Guyana" , 'd_code' => 592] , 
		['id' => 95 , 'sort_name' => "HT" , 'name' => "Haiti" , 'd_code' => 509] , 
		['id' => 96 , 'sort_name' => "HM" , 'name' => "Heard and McDonald Islands" , 'd_code' => 0] , 
		['id' => 97 , 'sort_name' => "HN" , 'name' => "Honduras" , 'd_code' => 504] , 
		['id' => 98 , 'sort_name' => "HK" , 'name' => "Hong Kong S.A.R." , 'd_code' => 852] , 
		['id' => 99 , 'sort_name' => "HU" , 'name' => "Hungary" , 'd_code' => 36] , 
		['id' => 100 , 'sort_name' => "IS" , 'name' => "Iceland" , 'd_code' => 354] , 
		['id' => 101 , 'sort_name' => "IN" , 'name' => "India" , 'd_code' => 91] , 
		['id' => 102 , 'sort_name' => "ID" , 'name' => "Indonesia" , 'd_code' => 62] , 
		['id' => 103 , 'sort_name' => "IR" , 'name' => "Iran" , 'd_code' => 98] , 
		['id' => 104 , 'sort_name' => "IQ" , 'name' => "Iraq" , 'd_code' => 964] , 
		['id' => 105 , 'sort_name' => "IE" , 'name' => "Ireland" , 'd_code' => 353] , 
		['id' => 106 , 'sort_name' => "IL" , 'name' => "Israel" , 'd_code' => 972] , 
		['id' => 107 , 'sort_name' => "IT" , 'name' => "Italy" , 'd_code' => 39] , 
		['id' => 108 , 'sort_name' => "JM" , 'name' => "Jamaica" , 'd_code' => 1876] , 
		['id' => 109 , 'sort_name' => "JP" , 'name' => "Japan" , 'd_code' => 81] , 
		['id' => 110 , 'sort_name' => "XJ" , 'name' => "Jersey" , 'd_code' => 44] , 
		['id' => 111 , 'sort_name' => "JO" , 'name' => "Jordan" , 'd_code' => 962] , 
		['id' => 112 , 'sort_name' => "KZ" , 'name' => "Kazakhstan" , 'd_code' => 7] , 
		['id' => 113 , 'sort_name' => "KE" , 'name' => "Kenya" , 'd_code' => 254] , 
		['id' => 114 , 'sort_name' => "KI" , 'name' => "Kiribati" , 'd_code' => 686] , 
		['id' => 115 , 'sort_name' => "KP" , 'name' => "Korea North" , 'd_code' => 850] , 
		['id' => 116 , 'sort_name' => "KR" , 'name' => "Korea South" , 'd_code' => 82] , 
		['id' => 117 , 'sort_name' => "KW" , 'name' => "Kuwait" , 'd_code' => 965] , 
		['id' => 118 , 'sort_name' => "KG" , 'name' => "Kyrgyzstan" , 'd_code' => 996] , 
		['id' => 119 , 'sort_name' => "LA" , 'name' => "Laos" , 'd_code' => 856] , 
		['id' => 120 , 'sort_name' => "LV" , 'name' => "Latvia" , 'd_code' => 371] , 
		['id' => 121 , 'sort_name' => "LB" , 'name' => "Lebanon" , 'd_code' => 961] , 
		['id' => 122 , 'sort_name' => "LS" , 'name' => "Lesotho" , 'd_code' => 266] , 
		['id' => 123 , 'sort_name' => "LR" , 'name' => "Liberia" , 'd_code' => 231] , 
		['id' => 124 , 'sort_name' => "LY" , 'name' => "Libya" , 'd_code' => 218] , 
		['id' => 125 , 'sort_name' => "LI" , 'name' => "Liechtenstein" , 'd_code' => 423] , 
		['id' => 126 , 'sort_name' => "LT" , 'name' => "Lithuania" , 'd_code' => 370] , 
		['id' => 127 , 'sort_name' => "LU" , 'name' => "Luxembourg" , 'd_code' => 352] , 
		['id' => 128 , 'sort_name' => "MO" , 'name' => "Macau S.A.R." , 'd_code' => 853] , 
		['id' => 129 , 'sort_name' => "MK" , 'name' => "Macedonia" , 'd_code' => 389] , 
		['id' => 130 , 'sort_name' => "MG" , 'name' => "Madagascar" , 'd_code' => 261] , 
		['id' => 131 , 'sort_name' => "MW" , 'name' => "Malawi" , 'd_code' => 265] , 
		['id' => 132 , 'sort_name' => "MY" , 'name' => "Malaysia" , 'd_code' => 60] , 
		['id' => 133 , 'sort_name' => "MV" , 'name' => "Maldives" , 'd_code' => 960] , 
		['id' => 134 , 'sort_name' => "ML" , 'name' => "Mali" , 'd_code' => 223] , 
		['id' => 135 , 'sort_name' => "MT" , 'name' => "Malta" , 'd_code' => 356] , 
		['id' => 136 , 'sort_name' => "XM" , 'name' => "Man (Isle of)" , 'd_code' => 44] , 
		['id' => 137 , 'sort_name' => "MH" , 'name' => "Marshall Islands" , 'd_code' => 692] , 
		['id' => 138 , 'sort_name' => "MQ" , 'name' => "Martinique" , 'd_code' => 596] , 
		['id' => 139 , 'sort_name' => "MR" , 'name' => "Mauritania" , 'd_code' => 222] , 
		['id' => 140 , 'sort_name' => "MU" , 'name' => "Mauritius" , 'd_code' => 230] , 
		['id' => 141 , 'sort_name' => "YT" , 'name' => "Mayotte" , 'd_code' => 269] , 
		['id' => 142 , 'sort_name' => "MX" , 'name' => "Mexico" , 'd_code' => 52] , 
		['id' => 143 , 'sort_name' => "FM" , 'name' => "Micronesia" , 'd_code' => 691] , 
		['id' => 144 , 'sort_name' => "MD" , 'name' => "Moldova" , 'd_code' => 373] , 
		['id' => 145 , 'sort_name' => "MC" , 'name' => "Monaco" , 'd_code' => 377] , 
		['id' => 146 , 'sort_name' => "MN" , 'name' => "Mongolia" , 'd_code' => 976] , 
		['id' => 147 , 'sort_name' => "MS" , 'name' => "Montserrat" , 'd_code' => 1664] , 
		['id' => 148 , 'sort_name' => "MA" , 'name' => "Morocco" , 'd_code' => 212] , 
		['id' => 149 , 'sort_name' => "MZ" , 'name' => "Mozambique" , 'd_code' => 258] , 
		['id' => 150 , 'sort_name' => "MM" , 'name' => "Myanmar" , 'd_code' => 95] , 
		['id' => 151 , 'sort_name' => "NA" , 'name' => "Namibia" , 'd_code' => 264] , 
		['id' => 152 , 'sort_name' => "NR" , 'name' => "Nauru" , 'd_code' => 674] , 
		['id' => 153 , 'sort_name' => "NP" , 'name' => "Nepal" , 'd_code' => 977] , 
		['id' => 154 , 'sort_name' => "AN" , 'name' => "Netherlands Antilles" , 'd_code' => 599] , 
		['id' => 155 , 'sort_name' => "NL" , 'name' => "Netherlands The" , 'd_code' => 31] , 
		['id' => 156 , 'sort_name' => "NC" , 'name' => "New Caledonia" , 'd_code' => 687] , 
		['id' => 157 , 'sort_name' => "NZ" , 'name' => "New Zealand" , 'd_code' => 64] , 
		['id' => 158 , 'sort_name' => "NI" , 'name' => "Nicaragua" , 'd_code' => 505] , 
		['id' => 159 , 'sort_name' => "NE" , 'name' => "Niger" , 'd_code' => 227] , 
		['id' => 160 , 'sort_name' => "NG" , 'name' => "Nigeria" , 'd_code' => 234] , 
		['id' => 161 , 'sort_name' => "NU" , 'name' => "Niue" , 'd_code' => 683] , 
		['id' => 162 , 'sort_name' => "NF" , 'name' => "Norfolk Island" , 'd_code' => 672] , 
		['id' => 163 , 'sort_name' => "MP" , 'name' => "Northern Mariana Islands" , 'd_code' => 1670] , 
		['id' => 164 , 'sort_name' => "NO" , 'name' => "Norway" , 'd_code' => 47] , 
		['id' => 165 , 'sort_name' => "OM" , 'name' => "Oman" , 'd_code' => 968] , 
		['id' => 166 , 'sort_name' => "PK" , 'name' => "Pakistan" , 'd_code' => 92] , 
		['id' => 167 , 'sort_name' => "PW" , 'name' => "Palau" , 'd_code' => 680] , 
		['id' => 168 , 'sort_name' => "PS" , 'name' => "Palestinian Territory Occupied" , 'd_code' => 970] , 
		['id' => 169 , 'sort_name' => "PA" , 'name' => "Panama" , 'd_code' => 507] , 
		['id' => 170 , 'sort_name' => "PG" , 'name' => "Papua new Guinea" , 'd_code' => 675] , 
		['id' => 171 , 'sort_name' => "PY" , 'name' => "Paraguay" , 'd_code' => 595] , 
		['id' => 172 , 'sort_name' => "PE" , 'name' => "Peru" , 'd_code' => 51] , 
		['id' => 173 , 'sort_name' => "PH" , 'name' => "Philippines" , 'd_code' => 63] , 
		['id' => 174 , 'sort_name' => "PN" , 'name' => "Pitcairn Island" , 'd_code' => 0] , 
		['id' => 175 , 'sort_name' => "PL" , 'name' => "Poland" , 'd_code' => 48] , 
		['id' => 176 , 'sort_name' => "PT" , 'name' => "Portugal" , 'd_code' => 351] , 
		['id' => 177 , 'sort_name' => "PR" , 'name' => "Puerto Rico" , 'd_code' => 1787] , 
		['id' => 178 , 'sort_name' => "QA" , 'name' => "Qatar" , 'd_code' => 974] , 
		['id' => 179 , 'sort_name' => "RE" , 'name' => "Reunion" , 'd_code' => 262] , 
		['id' => 180 , 'sort_name' => "RO" , 'name' => "Romania" , 'd_code' => 40] , 
		['id' => 181 , 'sort_name' => "RU" , 'name' => "Russia" , 'd_code' => 70] , 
		['id' => 182 , 'sort_name' => "RW" , 'name' => "Rwanda" , 'd_code' => 250] , 
		['id' => 183 , 'sort_name' => "SH" , 'name' => "Saint Helena" , 'd_code' => 290] , 
		['id' => 184 , 'sort_name' => "KN" , 'name' => "Saint Kitts And Nevis" , 'd_code' => 1869] , 
		['id' => 185 , 'sort_name' => "LC" , 'name' => "Saint Lucia" , 'd_code' => 1758] , 
		['id' => 186 , 'sort_name' => "PM" , 'name' => "Saint Pierre and Miquelon" , 'd_code' => 508] , 
		['id' => 187 , 'sort_name' => "VC" , 'name' => "Saint Vincent And The Grenadines" , 'd_code' => 1784] , 
		['id' => 188 , 'sort_name' => "WS" , 'name' => "Samoa" , 'd_code' => 684] , 
		['id' => 189 , 'sort_name' => "SM" , 'name' => "San Marino" , 'd_code' => 378] , 
		['id' => 190 , 'sort_name' => "ST" , 'name' => "Sao Tome and Principe" , 'd_code' => 239] , 
		['id' => 191 , 'sort_name' => "SA" , 'name' => "Saudi Arabia" , 'd_code' => 966] , 
		['id' => 192 , 'sort_name' => "SN" , 'name' => "Senegal" , 'd_code' => 221] , 
		['id' => 193 , 'sort_name' => "RS" , 'name' => "Serbia" , 'd_code' => 381] , 
		['id' => 194 , 'sort_name' => "SC" , 'name' => "Seychelles" , 'd_code' => 248] , 
		['id' => 195 , 'sort_name' => "SL" , 'name' => "Sierra Leone" , 'd_code' => 232] , 
		['id' => 196 , 'sort_name' => "SG" , 'name' => "Singapore" , 'd_code' => 65] , 
		['id' => 197 , 'sort_name' => "SK" , 'name' => "Slovakia" , 'd_code' => 421] , 
		['id' => 198 , 'sort_name' => "SI" , 'name' => "Slovenia" , 'd_code' => 386] , 
		['id' => 199 , 'sort_name' => "XG" , 'name' => "Smaller Territories of the UK" , 'd_code' => 44] , 
		['id' => 200 , 'sort_name' => "SB" , 'name' => "Solomon Islands" , 'd_code' => 677] , 
		['id' => 201 , 'sort_name' => "SO" , 'name' => "Somalia" , 'd_code' => 252] , 
		['id' => 202 , 'sort_name' => "ZA" , 'name' => "South Africa" , 'd_code' => 27] , 
		['id' => 203 , 'sort_name' => "GS" , 'name' => "South Georgia" , 'd_code' => 0] , 
		['id' => 204 , 'sort_name' => "SS" , 'name' => "South Sudan" , 'd_code' => 211] , 
		['id' => 205 , 'sort_name' => "ES" , 'name' => "Spain" , 'd_code' => 34] , 
		['id' => 206 , 'sort_name' => "LK" , 'name' => "Sri Lanka" , 'd_code' => 94] , 
		['id' => 207 , 'sort_name' => "SD" , 'name' => "Sudan" , 'd_code' => 249] , 
		['id' => 208 , 'sort_name' => "SR" , 'name' => "Suriname" , 'd_code' => 597] , 
		['id' => 209 , 'sort_name' => "SJ" , 'name' => "Svalbard And Jan Mayen Islands" , 'd_code' => 47] , 
		['id' => 210 , 'sort_name' => "SZ" , 'name' => "Swaziland" , 'd_code' => 268] , 
		['id' => 211 , 'sort_name' => "SE" , 'name' => "Sweden" , 'd_code' => 46] , 
		['id' => 212 , 'sort_name' => "CH" , 'name' => "Switzerland" , 'd_code' => 41] , 
		['id' => 213 , 'sort_name' => "SY" , 'name' => "Syria" , 'd_code' => 963] , 
		['id' => 214 , 'sort_name' => "TW" , 'name' => "Taiwan" , 'd_code' => 886] , 
		['id' => 215 , 'sort_name' => "TJ" , 'name' => "Tajikistan" , 'd_code' => 992] , 
		['id' => 216 , 'sort_name' => "TZ" , 'name' => "Tanzania" , 'd_code' => 255] , 
		['id' => 217 , 'sort_name' => "TH" , 'name' => "Thailand" , 'd_code' => 66] , 
		['id' => 218 , 'sort_name' => "TG" , 'name' => "Togo" , 'd_code' => 228] , 
		['id' => 219 , 'sort_name' => "TK" , 'name' => "Tokelau" , 'd_code' => 690] , 
		['id' => 220 , 'sort_name' => "TO" , 'name' => "Tonga" , 'd_code' => 676] , 
		['id' => 221 , 'sort_name' => "TT" , 'name' => "Trinidad And Tobago" , 'd_code' => 1868] , 
		['id' => 222 , 'sort_name' => "TN" , 'name' => "Tunisia" , 'd_code' => 216] , 
		['id' => 223 , 'sort_name' => "TR" , 'name' => "Turkey" , 'd_code' => 90] , 
		['id' => 224 , 'sort_name' => "TM" , 'name' => "Turkmenistan" , 'd_code' => 7370] , 
		['id' => 225 , 'sort_name' => "TC" , 'name' => "Turks And Caicos Islands" , 'd_code' => 1649] , 
		['id' => 226 , 'sort_name' => "TV" , 'name' => "Tuvalu" , 'd_code' => 688] , 
		['id' => 227 , 'sort_name' => "UG" , 'name' => "Uganda" , 'd_code' => 256] , 
		['id' => 228 , 'sort_name' => "UA" , 'name' => "Ukraine" , 'd_code' => 380] , 
		['id' => 229 , 'sort_name' => "AE" , 'name' => "United Arab Emirates" , 'd_code' => 971] , 
		['id' => 230 , 'sort_name' => "GB" , 'name' => "United Kingdom" , 'd_code' => 44] , 
		['id' => 231 , 'sort_name' => "US" , 'name' => "United States" , 'd_code' => 1] , 
		['id' => 232 , 'sort_name' => "UM" , 'name' => "United States Minor Outlying Islands" , 'd_code' => 1] , 
		['id' => 233 , 'sort_name' => "UY" , 'name' => "Uruguay" , 'd_code' => 598] , 
		['id' => 234 , 'sort_name' => "UZ" , 'name' => "Uzbekistan" , 'd_code' => 998] , 
		['id' => 235 , 'sort_name' => "VU" , 'name' => "Vanuatu" , 'd_code' => 678] , 
		['id' => 236 , 'sort_name' => "VA" , 'name' => "Vatican City State (Holy See)" , 'd_code' => 39] , 
		['id' => 237 , 'sort_name' => "VE" , 'name' => "Venezuela" , 'd_code' => 58] , 
		['id' => 238 , 'sort_name' => "VN" , 'name' => "Vietnam" , 'd_code' => 84] , 
		['id' => 239 , 'sort_name' => "VG" , 'name' => "Virgin Islands (British)" , 'd_code' => 1284] , 
		['id' => 240 , 'sort_name' => "VI" , 'name' => "Virgin Islands (US)" , 'd_code' => 1340] , 
		['id' => 241 , 'sort_name' => "WF" , 'name' => "Wallis And Futuna Islands" , 'd_code' => 681] , 
		['id' => 242 , 'sort_name' => "EH" , 'name' => "Western Sahara" , 'd_code' => 212] , 
		['id' => 243 , 'sort_name' => "YE" , 'name' => "Yemen" , 'd_code' => 967] , 
		['id' => 244 , 'sort_name' => "YU" , 'name' => "Yugoslavia" , 'd_code' => 38] , 
		['id' => 245 , 'sort_name' => "ZM" , 'name' => "Zambia" , 'd_code' => 260] , 
		['id' => 246 , 'sort_name' => "ZW" , 'name' => "Zimbabwe" , 'd_code' => 26] , 
		];